In [1]:
import pandas as pd

In [1]:
from xfoil import XFoil
xf = XFoil()

## coords

In [1]:
import numpy as np
import matplotlib.pyplot as plt
dataset_npz_path = [
    "dataset/standardized_upsampling_coords.npz",  # 4338データ(4338, 496), ["coords", "mean", "std"], 標準化済み
    "dataset/upsampling_coords.npy",  # 4338データ, 直接coordsのarray, shape=(4338, 496), 標準化なし
    "dataset/standardized_coords.npz",  # 3709データ(3709, 496), ["coords", "mean", "std"], 標準化済み
    "dataset/coords.npy",  # 3709データ, 直接coordsのarray, shape=(3709, 496), 標準化なし
    "dataset/yonekura_bezier_coords.npy",  # 3696データ, 直接coordsのarray, shape=(3696, 248, 2), 標準化済み
    "dataset/yonekura_coords.npy",  # 3551データ, 直接coordsのarray, shape=(3551, 496), 標準化なし
    "dataset/yonekura_standardized_coords.npz",  # 3551データ(3551, 496), ["coords", "mean", "std"], 標準化済み
]
coords_npz = np.load(dataset_npz_path[0])
coords_npz

NpzFile 'dataset/standardized_upsampling_coords.npz' with keys: coords, mean, std

In [7]:
coords_npz["coords"][0]

array([ 1.00000000e+00, -9.41959111e-01, -9.53447536e-01, -9.63489577e-01,
       -9.72588132e-01, -9.80902888e-01, -9.88415739e-01, -9.95110455e-01,
       -1.00097359e+00, -1.00599980e+00, -1.01019020e+00, -1.01355196e+00,
       -1.01609765e+00, -1.01784445e+00, -1.01881343e+00, -1.01902880e+00,
       -1.01851713e+00, -1.01730674e+00, -1.01542699e+00, -1.01290776e+00,
       -1.00977894e+00, -1.00606999e+00, -1.00180955e+00, -9.97025191e-01,
       -9.91743115e-01, -9.85987988e-01, -9.79782779e-01, -9.73148655e-01,
       -9.66104897e-01, -9.58668853e-01, -9.50855904e-01, -9.42679453e-01,
       -9.34150928e-01, -9.25279791e-01, -9.16073552e-01, -9.06537800e-01,
       -8.96676216e-01, -8.86490598e-01, -8.75980865e-01, -8.65145032e-01,
       -8.53979130e-01, -8.42477012e-01, -8.30629931e-01, -8.18425712e-01,
       -8.05847107e-01, -7.92868664e-01, -7.79450762e-01, -7.65528411e-01,
       -7.50990581e-01, -7.35643328e-01, -7.19229225e-01, -7.01280585e-01,
       -6.80830046e-01, -

In [5]:
coords_npz["coords"].reshape(-1,2,248)[0]

array([[ 1.00000000e+00, -9.41959111e-01, -9.53447536e-01,
        -9.63489577e-01, -9.72588132e-01, -9.80902888e-01,
        -9.88415739e-01, -9.95110455e-01, -1.00097359e+00,
        -1.00599980e+00, -1.01019020e+00, -1.01355196e+00,
        -1.01609765e+00, -1.01784445e+00, -1.01881343e+00,
        -1.01902880e+00, -1.01851713e+00, -1.01730674e+00,
        -1.01542699e+00, -1.01290776e+00, -1.00977894e+00,
        -1.00606999e+00, -1.00180955e+00, -9.97025191e-01,
        -9.91743115e-01, -9.85987988e-01, -9.79782779e-01,
        -9.73148655e-01, -9.66104897e-01, -9.58668853e-01,
        -9.50855904e-01, -9.42679453e-01, -9.34150928e-01,
        -9.25279791e-01, -9.16073552e-01, -9.06537800e-01,
        -8.96676216e-01, -8.86490598e-01, -8.75980865e-01,
        -8.65145032e-01, -8.53979130e-01, -8.42477012e-01,
        -8.30629931e-01, -8.18425712e-01, -8.05847107e-01,
        -7.92868664e-01, -7.79450762e-01, -7.65528411e-01,
        -7.50990581e-01, -7.35643328e-01, -7.19229225e-0

In [104]:
def show_coord(coord):
    xs, ys = coord.reshape(2, -1)
    plt.plot(xs, ys)
    plt.show()

show_coord(coords_npz[0])

In [97]:
# 時計回り
# yonekura_standardized_coords.npz
# (0,0): 120, (1,0): 248
print(coords_npz["coords"][0][119])
print(coords_npz["coords"][0][119+248])
print(coords_npz["coords"][0][119+128])
print(coords_npz["coords"][0][119+128+248])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
# 反時計回り
# dataset/standardized_upsampling_coords.npz
# dataset/standardized_coords.npz
# (1,0): 1, (0,0): 129

# 1点目のx,y座標
print(coords_npz["coords"][0][0])
print(coords_npz["coords"][0][0+248])
# 127点目のx,y座標
print(coords_npz["coords"][0][128])
print(coords_npz["coords"][0][128 + 248])

1.0
0.0
0.0
0.0


## perfs

In [4]:
import numpy as np

perfs_path = [
    "dataset/perfs.npy",  # (3709,)
    "dataset/standardized_perfs.npz",  # ["perfs"(3709,), "mean" array(0.68415253), "std" array(0.3880009)]
    "dataset/standardized_upsampling_perfs.npz",  # ["perfs"(4338,), "mean" array(0.7899429090113754), "std" array(0.4424838352594898)]
    "dataset/upsampling_perfs.npy",  # (4338,)
    "dataset/yonekura_bezier_perfs.npy",  # (3696,)
    "dataset/yonekura_perfs.npy",  # (3551,)
    "dataset/yonekura_standardized_perfs.npz",  # ["perfs"(3551,), "mean" array(0.6926046582232329), "std" array(0.38716456936649757)]
]
perfs_np = np.load(perfs_path[6])
perfs_np

NpzFile 'dataset/yonekura_standardized_perfs.npz' with keys: perfs, mean, std

In [7]:
perfs_np["mean"].shape

()

In [2]:
import numpy as np
test_data = np.random.randn(10, 496)
l2_test = np.linalg.norm(test_data - test_data.mean(axis=0), axis=1)
l1_test = np.sum(np.abs(test_data - test_data.mean(axis=0)), axis=1)
print("Test L2 Norms:", l2_test)
print("Test L1 Norms:", l1_test)

Test L2 Norms: [19.61005712 20.71497286 21.20716126 21.63127624 21.73954307 21.11096957
 21.83016638 20.98486069 22.10205067 21.45195276]
Test L1 Norms: [349.55961135 367.16181523 375.95185607 381.99170712 381.67109357
 382.30387673 394.77380461 372.2125037  400.17048774 386.31426448]


In [55]:
valid_mask = np.array([True, True, False, True, True])
gen_coords = np.array(
    [
        [[1.0, 0.99997225, 0.99978431, -0.00379859, -0.00376016, -0.00372542]],
        [[1.0, 1.00007748, 0.9999071, -0.00379859, -0.00376016, -0.00372542]],
        [[1.0, 1.00112764, 1.00097445, -0.0035629, -0.00356974, -0.00350204]],
        [[1.0, 0.99994374, 0.99974587, -0.00379859, -0.00376016, -0.00372542]],
        [[1.0, 1.00010877, 0.99991402, -0.00379859, -0.00376016, -0.00372542]],
    ]
)
gen_coords[valid_mask].mean(axis=0)

array([[ 1.        ,  1.00002556,  0.99983782, -0.00379859, -0.00376016,
        -0.00372542]])

In [58]:
diversity_l2 = (
    np.mean(np.linalg.norm(gen_coords[valid_mask] - gen_coords[valid_mask].mean(axis=0), axis=2))
    if valid_mask.any()
    else np.nan
)
diversity_l2

np.float64(9.95051410474715e-05)

In [59]:
diversity_l1 = (
    np.mean(np.sum(np.abs(gen_coords[valid_mask] - gen_coords[valid_mask].mean(axis=0)), axis=2))
    if valid_mask.any()
    else np.nan
)
diversity_l1

np.float64(0.00014030000000000986)

In [60]:
valid_mask = np.array([True, True, False, True, True])
gen_coords = np.array(
    [
        [1.0, 0.99997225, 0.99978431, -0.00379859, -0.00376016, -0.00372542],
        [1.0, 1.00007748, 0.9999071, -0.00379859, -0.00376016, -0.00372542],
        [1.0, 1.00112764, 1.00097445, -0.0035629, -0.00356974, -0.00350204],
        [1.0, 0.99994374, 0.99974587, -0.00379859, -0.00376016, -0.00372542],
        [1.0, 1.00010877, 0.99991402, -0.00379859, -0.00376016, -0.00372542],
    ]
)
gen_coords[valid_mask].mean(axis=0)

array([ 1.        ,  1.00002556,  0.99983782, -0.00379859, -0.00376016,
       -0.00372542])

In [62]:
diversity_l2 = (
    np.mean(np.linalg.norm(gen_coords[valid_mask] - gen_coords[valid_mask].mean(axis=0), axis=1))
    if valid_mask.any()
    else np.nan
)
print(diversity_l2)

9.95051410474715e-05


In [63]:
mu_d = np.linalg.norm(gen_coords[valid_mask] - np.mean(gen_coords[valid_mask], axis=0)) / len(gen_coords[valid_mask])

In [30]:
diversity_l1 = (
    np.mean(np.sum(np.abs(gen_coords[valid_mask] - gen_coords[valid_mask].mean(axis=0)), axis=1))
    if valid_mask.any()
    else np.nan
)
print(diversity_l1)

0.00014030000000000986
